### ISSUE TITLE
Generation counter not counting?

### ISSUE THREAD

**Issue by ann-brown** [severian42/Vodalus-Expert-LLM-Forge#1]
I think I'm supposed to get 1 generation per topic? I have a solid 48 / 15 topics and it's still calling it 'Generation 1'. Not too big an issue with a local model, worse if I left it running with a cloud provider API modded in.

**Comment by severian42** [comment]
Great catch! The 'Generation 1' actually has to do with the number of workers you have set to generate in the params.py. Since we are running local and most machines are limited, it is set at 1; so it'll run as if you are 'batch processing' just 1 at a time. You can change this parameter in the params.py file but it only works best for batching if you can run concurrently or want to tap into an enterprise API
